#!/usr/bin/env python3
"""Prepare local A/B synthetic catalogs with the existing approved-photo publisher.

Usage: python -B OfficialWindowService/tools/prepare_fixture.py --output C:/local-review/new-batch

The output parent must already exist, and the new directory must be outside
this checkout. Only first/, updated/, and paused/ are retained. Originals are
temporary, generated shapes; no real cat photos or contributor consent are
represented. This tool never uploads, publishes, contacts a service, or deletes
old output. On failure, any partial new batch must not be used or published.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timedelta, timezone
import importlib.util
from pathlib import Path
import sys
import tempfile

from PIL import Image, ImageDraw, ImageFont


REPO_ROOT = Path(__file__).resolve().parents[2]
PUBLISHER_PATH = REPO_ROOT / "NekoWidget" / "official-window-tools" / "build_catalog.py"


def load_publisher():
    spec = importlib.util.spec_from_file_location("official_window_fixture_publisher", PUBLISHER_PATH)
    if spec is None or spec.loader is None:
        raise ValueError("the existing local publisher could not be loaded")
    publisher = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(publisher)
    return publisher


def draw_source(path: Path, label: str) -> None:
    """Draw visibly synthetic shapes and text using Pillow's bundled font."""
    image = Image.new("RGB", (1024, 1024), "#f8f2e7")
    drawing = ImageDraw.Draw(image)
    if label == "A":
        drawing.ellipse((176, 176, 848, 848), fill="#e15b25")
    else:
        drawing.rectangle((176, 176, 848, 848), fill="#246bce")
    drawing.text((512, 512), label, fill="white", anchor="mm", font=ImageFont.load_default(size=300))
    font = ImageFont.load_default(size=42)
    drawing.text((512, 72), "SYNTHETIC TEST IMAGE", fill="#202020", anchor="mm", font=font)
    drawing.text((512, 954), "NOT A REAL CAT PHOTO", fill="#202020", anchor="mm", font=font)
    image.save(path, format="PNG")


def prepare_fixture(output: Path, *, now: datetime | None = None) -> dict:
    publisher = load_publisher()
    if output.exists() or output.is_symlink():
        raise ValueError("output already exists; choose a new directory")
    parent = publisher.local_path(output.parent)
    if not parent.is_dir() or output.name in {"", ".", ".."}:
        raise ValueError("output requires an existing local parent directory")
    destination = parent / output.name
    if destination.is_relative_to(REPO_ROOT):
        raise ValueError("keep generated fixtures outside this checkout")
    base = now if now is not None else datetime.now(timezone.utc)
    if base.tzinfo is None or base.utcoffset() is None:
        raise ValueError("generation time must include a timezone")
    base = base.astimezone(timezone.utc).replace(microsecond=0)
    # The last catalog is only two seconds ahead of generation, within the
    # client's 300-second future allowance. Do not pretend to wait or publish.
    updated_at = base + timedelta(seconds=1)
    paused_at = base + timedelta(seconds=2)

    def photo(label: str, published: datetime) -> dict:
        return {
            "id": f"synthetic-test-{label.lower()}",
            "catID": f"synthetic-shape-{label.lower()}",
            "catName": f"合成テスト画像 {label}",
            "credit": "コード生成のテスト図形（実在猫・提供者なし）",
            "caption": f"表示・更新確認用の {label}。実際の猫写真ではありません。",
            "publishedAt": publisher.utc_string(published),
            "expiresAt": publisher.utc_string(published + timedelta(days=7)),
            "sourceFilename": f"{label}.png",
            # Approval is solely for these script-generated test pixels.
            "publicationApproved": True,
            "internal": {"source": "synthetic fixture generated by prepare_fixture.py"},
        }

    with tempfile.TemporaryDirectory(prefix="official-window-synthetic-") as temporary:
        originals = Path(temporary)
        draw_source(originals / "A.png", "A")
        draw_source(originals / "B.png", "B")
        first_photo = photo("A", base - timedelta(minutes=1))
        second_photo = photo("B", updated_at)
        destination.mkdir(exist_ok=False)
        first = publisher.build_catalog(
            destination / "first", document={"photos": [first_photo]},
            images_dir=originals, now=base,
        )
        updated = publisher.build_catalog(
            destination / "updated", document={"photos": [first_photo, second_photo]},
            images_dir=originals, now=updated_at,
        )
        paused = publisher.build_catalog(destination / "paused", paused=True, now=paused_at)
    return {"first": first, "updated": updated, "paused": paused}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="既存publisherで合成画像A/Bのローカル確認バッチを作ります。公開はしません。",
        epilog="first=Aのみ、updated=Bが新着、paused=停止。catalogは48時間有効。実行失敗時の部分出力は使用しないでください。",
    )
    parser.add_argument("--output", required=True, type=Path,
                        help="worktree外の未作成ローカルディレクトリ（親は作成済み）")
    args = parser.parse_args(argv)
    try:
        prepare_fixture(args.output)
    except (ValueError, OSError):
        print("Fixture preparation failed. Use a new local directory outside the checkout; "
              "do not use or publish partial output.", file=sys.stderr)
        return 1
    print("Prepared synthetic local fixtures: first (A), updated (B, A), paused (empty). "
          "Nothing was uploaded or published.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
