#!/usr/bin/env python3
"""Write non-secret evidence for one workflow-produced signed local-only archive."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import plistlib
import re
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path


EXPECTED_ARTIFACT_FILENAME = "NekoWidget-signed-artifacts.tar.gz.enc"
EXPECTED_INFO_FILENAME = "NekoWidget-processed-app-info.plist"
EXPECTED_EVIDENCE_FILENAME = "local-only-release-evidence.json"
EXPECTED_REPOSITORY = "soso-so-27/neko-widget"
MINIMUM_ARTIFACT_BYTES = 1_000_000


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def git_text(repository: Path, *arguments: str) -> str:
    return subprocess.run(
        ["git", "-C", str(repository), *arguments],
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
    ).stdout.strip()


def bool_argument(value: str) -> bool:
    if value == "true":
        return True
    if value == "false":
        return False
    raise argparse.ArgumentTypeError("expected true or false")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repository", type=Path, required=True)
    parser.add_argument("--info-plist", type=Path, required=True)
    parser.add_argument("--artifact", type=Path, required=True)
    parser.add_argument("--output-directory", type=Path, required=True)
    parser.add_argument("--source-commit", required=True)
    parser.add_argument("--version", required=True)
    parser.add_argument("--build-number", required=True)
    parser.add_argument("--release-mode", required=True)
    parser.add_argument("--run-id", type=int, required=True)
    parser.add_argument("--run-attempt", type=int, required=True)
    parser.add_argument("--event", required=True)
    parser.add_argument("--upload-to-testflight", type=bool_argument, required=True)
    parser.add_argument("--retain-signed-artifacts", type=bool_argument, required=True)
    args = parser.parse_args()

    if os.environ.get("GITHUB_ACTIONS") != "true":
        raise SystemExit("Release evidence must be generated by GitHub Actions.")
    expected_environment = {
        "GITHUB_SHA": args.source_commit,
        "GITHUB_RUN_ID": str(args.run_id),
        "GITHUB_RUN_ATTEMPT": str(args.run_attempt),
        "GITHUB_EVENT_NAME": args.event,
        "GITHUB_REPOSITORY": EXPECTED_REPOSITORY,
    }
    for key, expected in expected_environment.items():
        if os.environ.get(key) != expected:
            raise SystemExit(f"{key} does not match the explicit evidence input.")

    if args.release_mode != "disabled":
        raise SystemExit("Local-only release evidence requires release_mode=disabled.")
    if args.event != "workflow_dispatch":
        raise SystemExit("Release evidence requires workflow_dispatch.")
    if not args.retain_signed_artifacts:
        raise SystemExit("Release evidence requires retained signed artifacts.")
    if not re.fullmatch(r"[0-9a-f]{40}", args.source_commit):
        raise SystemExit("source_commit must be a lowercase full SHA.")
    if git_text(args.repository, "rev-parse", "HEAD") != args.source_commit:
        raise SystemExit("source_commit must exactly equal repository HEAD.")
    if git_text(args.repository, "cat-file", "-t", args.source_commit) != "commit":
        raise SystemExit("source_commit is not a commit in this repository.")
    if not re.fullmatch(r"[1-9][0-9]*", args.build_number):
        raise SystemExit("build_number must be a positive integer string.")
    if args.run_id < 1_000 or args.run_attempt < 1:
        raise SystemExit("GitHub run identifiers are invalid.")

    if args.artifact.name != EXPECTED_ARTIFACT_FILENAME or not args.artifact.is_file():
        raise SystemExit("Encrypted signed artifact is missing or has the wrong filename.")
    artifact_size = args.artifact.stat().st_size
    if artifact_size < MINIMUM_ARTIFACT_BYTES:
        raise SystemExit("Encrypted signed artifact is implausibly small.")
    if not args.info_plist.is_file():
        raise SystemExit("Processed App Info.plist is missing.")
    try:
        info = plistlib.loads(args.info_plist.read_bytes())
    except plistlib.InvalidFileException as error:
        raise SystemExit(f"Processed App Info.plist is invalid: {error}") from error
    expected_info = {
        "CFBundleIdentifier": "jp.nekowidget.app",
        "CFBundleDisplayName": "ねこのまど",
        "CFBundleShortVersionString": args.version,
        "CFBundleVersion": args.build_number,
        "SharingReleaseMode": "disabled",
        "SharingFeatureEnabled": "NO",
        "SharingMediaEnabled": "NO",
        "SharingShareExtensionHandoffEnabled": "NO",
        "SharingShareExtensionSendEnabled": "NO",
        "SharingReviewPreviewEnabled": "NO",
        "SharingAPIBaseURL": "",
        "SharingModerationKeyID": "",
        "SharingModerationPublicKey": "",
        "SharingPrivacyURL": "",
        "SharingSupportURL": "",
        "SharingCommunityStandardsURL": "",
        "AppPrivacyURL": "https://soso-so-27.github.io/neko-widget/app/privacy/",
        "AppSupportURL": "https://soso-so-27.github.io/neko-widget/app/support/",
        "ITSAppUsesNonExemptEncryption": False,
    }
    for key, expected in expected_info.items():
        if not isinstance(info, dict) or info.get(key) != expected:
            raise SystemExit(f"Processed App Info.plist mismatch for {key}.")

    args.output_directory.mkdir(parents=True, exist_ok=True)
    processed_output = args.output_directory / EXPECTED_INFO_FILENAME
    shutil.copyfile(args.info_plist, processed_output)
    evidence = {
        "schema_version": 1,
        "generated_at_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "repository": EXPECTED_REPOSITORY,
        "source_commit": args.source_commit,
        "version": args.version,
        "build_number": args.build_number,
        "release_mode": args.release_mode,
        "ci_run": {
            "workflow": ".github/workflows/testflight.yml",
            "run_id": args.run_id,
            "run_attempt": args.run_attempt,
            "event": args.event,
            "head_sha": args.source_commit,
            "run_url": (
                f"https://github.com/{EXPECTED_REPOSITORY}/actions/runs/{args.run_id}"
            ),
            "status": "completed",
            "conclusion": "success",
            "upload_to_testflight": args.upload_to_testflight,
            "app_store_upload_passed": args.upload_to_testflight,
            "retain_signed_artifacts": args.retain_signed_artifacts,
        },
        "validations": {
            "archive_validator": "NekoWidget/ci/validate-sharing-release.py",
            "archive_validator_passed": True,
            "signature_validation_passed": True,
            "artifact_encryption_verified": True,
        },
        "signed_artifact": {
            "filename": EXPECTED_ARTIFACT_FILENAME,
            "sha256": sha256_file(args.artifact),
            "size_bytes": artifact_size,
            "encrypted": True,
        },
        "processed_app_info": {
            "filename": EXPECTED_INFO_FILENAME,
            "sha256": sha256_file(processed_output),
        },
    }
    output = args.output_directory / EXPECTED_EVIDENCE_FILENAME
    temporary = output.with_suffix(".json.tmp")
    temporary.write_text(
        json.dumps(evidence, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    temporary.replace(output)
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
