const keys = ['BILLING_VERIFIER_SHARED_SECRET', 'APPLE_ROOT_CERTIFICATES_BASE64_JSON',
  'BILLING_STORE_ENVIRONMENT', 'BILLING_BUNDLE_ID', 'BILLING_APP_APPLE_ID', 'BILLING_SUBSCRIPTION_GROUP_ID',
  'BILLING_MONTHLY_PRODUCT_ID', 'BILLING_ANNUAL_PRODUCT_ID', 'BILLING_NOTIFICATION_VERIFIER_RUNTIME_ENABLED',
  'BILLING_NOTIFICATION_HISTORY_RUNTIME_ENABLED', 'BILLING_SUBSCRIPTION_STATUS_RUNTIME_ENABLED',
  'BILLING_ACCOUNT_RECOVERY_VERIFIER_RUNTIME_ENABLED'];
const serverKeys = ['APP_STORE_SERVER_API_PRIVATE_KEY', 'APP_STORE_SERVER_API_KEY_ID', 'APP_STORE_SERVER_API_ISSUER_ID'];
export function containerEnvironment(env) {
  const selected = env.BILLING_NOTIFICATION_HISTORY_RUNTIME_ENABLED === 'YES'
    || env.BILLING_SUBSCRIPTION_STATUS_RUNTIME_ENABLED === 'YES' ? [...keys, ...serverKeys] : keys;
  const values = Object.fromEntries(selected.filter(key => typeof env[key] === 'string').map(key => [key, env[key]]));
  return { ...values, BILLING_VERIFIER_RUNTIME_ENABLED: 'YES', BILLING_VERIFIER_CONTAINER_RUNTIME_ENABLED: 'YES' };
}
