/** Data-free local operator enrollment page. Never renders a token or private key. */
export function localModerationEnrollmentConsole(): Response {
  const nonce = crypto.randomUUID().replaceAll("-", "");
  return new Response(`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>運営者の登録｜ねこのまど</title><style nonce="${nonce}">
:root{font-family:system-ui,sans-serif;color:#19362e;background:#f3f5f1;color-scheme:light}*{box-sizing:border-box}
body{margin:0}main{max-width:800px;padding:36px 24px 64px;margin:auto}h1{font-size:30px;margin:8px 0 24px}h2{font-size:20px;margin-top:0}p{line-height:1.7}
.eyebrow,.muted{color:#546a62;font-size:14px}.note{background:#e5ede7;border-radius:12px;padding:16px 20px}.card{margin-top:24px;border:1px solid #d4dfd7;background:white;border-radius:16px;padding:24px}
ol{padding-left:24px;line-height:2}.active{font-weight:700;color:#245b47}.done{color:#546a62}button,a.action{display:inline-block;font:inherit;font-weight:600;border:1px solid #b5c7bb;border-radius:10px;padding:12px 18px;min-height:46px;color:#214e3e;background:white;cursor:pointer;text-decoration:none}
button.primary{color:white;background:#245b47;border-color:#245b47}button:disabled{opacity:.5;cursor:default}button:focus-visible,a:focus-visible,textarea:focus-visible{outline:3px solid #be742e;outline-offset:3px}
textarea{display:block;width:100%;height:140px;border:1px solid #b5c7bb;border-radius:8px;padding:12px;font:14px/1.5 monospace;resize:vertical;margin:8px 0 16px}label{font-weight:600}
#status{min-height:28px;line-height:1.7}code{overflow-wrap:anywhere}.row{display:flex;flex-wrap:wrap;gap:12px}.success{color:#245b47}footer{margin-top:28px;color:#546a62;font-size:14px}
@media(max-width:560px){main{padding:24px 16px 48px}h1{font-size:25px}.card{padding:18px}button,a.action{width:100%;text-align:center}}
[hidden]{display:none!important}
</style></head><body><main>
<div class="eyebrow">ねこのまど / 運営用</div><h1>運営者の登録</h1>
<div class="note"><strong>ローカル検証版</strong><p>登録する鍵を確認し、2つの承認署名を照合します。クラウドの運営権限は変更しません。</p></div>
<ol aria-label="登録の手順"><li id="step1" class="active">認証器を登録</li><li id="step2">同じ鍵で所有を確認</li><li id="step3">承認署名を照合</li></ol>
<section class="card"><h2 id="heading">運営用の認証器を準備してください</h2>
<p id="instruction">本人確認に対応したセキュリティキーで、登録する鍵とその所有を確認します。途中で画面を閉じても、登録の取消しにはなりません。</p>
<p id="status" role="status" aria-live="polite">「登録を準備する」から始めてください。</p>
<div class="row"><button id="start" class="primary">登録を準備する</button><button id="possession" class="primary" hidden>同じ鍵で所有を確認</button><button id="check" hidden>この申込の結果を確認</button></div>
<div id="approval" hidden><p>有効期限：<span id="expires"></span></p><p class="muted">申込の照合番号：<code id="requestHash"></code></p>
<p>申込ファイルを確認し、指定された2つの承認鍵で署名してください。秘密鍵やログイン情報をこの画面へ貼り付けないでください。</p>
<button id="download">承認用の申込を保存</button><p></p><label for="signatures">承認署名のファイル内容</label>
<textarea id="signatures" spellcheck="false" autocomplete="off" placeholder='{"approvals":[…]}'></textarea>
<button id="admit" class="primary">署名を照合して登録を確定</button></div>
<div id="complete" hidden><p class="success"><strong>ローカルの登録記録を確認しました。</strong></p><p>通報の確認画面で、現在の本人認証と権限を改めて確認します。</p><a class="action" href="/operator/console">通報の確認へ</a></div>
</section><footer>通信が途切れた場合は、同じ申込の結果を確認してください。署名や登録を自動で繰り返すことはありません。</footer>
</main><script nonce="${nonce}">
"use strict";
const byId=id=>document.getElementById(id), start=byId('start'), possession=byId('possession'), check=byId('check'), approval=byId('approval'), complete=byId('complete'), status=byId('status'), signatures=byId('signatures'), admit=byId('admit');
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/, hash=/^[0-9a-f]{64}$/;
let generation=0,controller=null,busy=false,ceremonyID=null,request=null,next=null,credentialID=null,expiryTimer=null;
function lock(value){busy=value;for(const b of document.querySelectorAll('button'))b.disabled=value}
function hideDetails(){signatures.value='';approval.hidden=true;complete.hidden=true;possession.hidden=true;next=null;credentialID=null}
function stop(message){generation++;controller?.abort();clearTimeout(expiryTimer);hideDetails();lock(false);start.disabled=true;check.hidden=!ceremonyID;status.textContent=message}
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop('画面を離れたため表示を消しました。この申込の結果を確認してください。登録を取り消したという意味ではありません。')});
window.addEventListener('pagehide',()=>stop('この申込の結果を確認してください。'));
function armExpiry(expiresAt){clearTimeout(expiryTimer);const remaining=expiresAt*1000-Date.now();if(remaining<=0)throw Error('expired');expiryTimer=setTimeout(()=>stop('準備の有効期限が過ぎました。この申込の結果を確認してください。'),remaining)}
function steps(current){for(let i=1;i<=3;i++)byId('step'+i).className=i===current?'active':i<current?'done':''}
function begin(){const epoch=++generation;controller?.abort();controller=new AbortController();lock(true);return epoch}
function failed(){hideDetails();start.disabled=true;check.hidden=!ceremonyID;status.textContent=ceremonyID?'結果を確認できません。この申込の結果を確認してください。署名は再送しません。':'準備の結果を確認できません。運営用のログインと接続を確認してください。'}
async function api(path,body){const response=await fetch('/operator/v1/enrollment/'+path,{method:'POST',credentials:'same-origin',redirect:'error',cache:'no-store',signal:AbortSignal.any([controller.signal,AbortSignal.timeout(20000)]),...(body===undefined?{}:{headers:{'Content-Type':'application/json'},body})});if(!response.ok)throw Error('request');return response.json()}
function decode(value){if(typeof value!=='string'||value.length>2048||!/^[A-Za-z0-9_-]+$/.test(value))throw Error('bytes');return Uint8Array.from(atob(value.replaceAll('-','+').replaceAll('_','/')+'='.repeat((4-value.length%4)%4)),c=>c.charCodeAt(0))}
function encode(value){return btoa(String.fromCharCode(...new Uint8Array(value))).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'')}
function challenge(value,phase){if(!value||value.phase!==phase||!uuid.test(value.ceremonyID)||!uuid.test(value.challengeID)||typeof value.challenge!=='string'||decode(value.challenge).length!==32||typeof value.rpId!=='string'||!/^[a-z0-9.-]{1,253}$/.test(value.rpId)||value.rpId.includes('..')||!(value.rpId===location.hostname||location.hostname.endsWith('.'+value.rpId))||!Number.isSafeInteger(value.expiresAt)||value.expiresAt*1000<=Date.now()||value.expiresAt*1000>Date.now()+900000||value.enrollmentAdmissionAuthorized!==false)throw Error('challenge');if(ceremonyID&&value.ceremonyID!==ceremonyID)throw Error('binding');return value}
function showRequest(value,historical=false){if(!value||value.kind!=='unadmitted-local-initial-enrollment-request'||value.ceremonyID!==ceremonyID||!uuid.test(value.requestID)||!hash.test(value.canonicalRequestSHA256)||!Number.isSafeInteger(value.expiresAt)||value.enrollmentAdmissionAuthorized!==false||!Array.isArray(value.approvalTranscripts)||value.approvalTranscripts.length!==2||value.approvalTranscripts.some(a=>typeof a.keyID!=='string'||!Number.isSafeInteger(a.revision)||typeof a.transcriptBase64url!=='string'))throw Error('request');if(request&&(value.requestID!==request.requestID||value.canonicalRequestSHA256!==request.canonicalRequestSHA256))throw Error('binding');if(historical){clearTimeout(expiryTimer);request=value;return}armExpiry(value.expiresAt);request=value;steps(3);byId('heading').textContent='承認署名を確認してください';byId('instruction').textContent='鍵の登録と所有確認は完了しました。2つの承認署名が一致するまで登録は確定しません。';byId('expires').textContent=new Date(value.expiresAt*1000).toLocaleString('ja-JP');byId('requestHash').textContent=value.canonicalRequestSHA256;approval.hidden=false;possession.hidden=true;start.hidden=true;check.hidden=false;status.textContent='この申込に対応する承認署名を準備してください。'}
function showReceipt(value){if(!value||value.kind!=='locally-admitted-initial-operator'||value.ceremonyID!==ceremonyID||!uuid.test(value.requestID)||!uuid.test(value.admissionID)||!hash.test(value.canonicalRequestSHA256)||!hash.test(value.admissionProvenanceSHA256)||!Number.isSafeInteger(value.admittedAt)||value.realHumanVerified!==false||value.hardwareProvenanceVerified!==false)throw Error('receipt');if(!request||value.requestID!==request.requestID||value.canonicalRequestSHA256!==request.canonicalRequestSHA256)throw Error('binding');clearTimeout(expiryTimer);hideDetails();start.hidden=true;check.hidden=true;complete.hidden=false;steps(4);byId('heading').textContent='登録を確認しました';byId('instruction').textContent='この申込と承認署名に一致する登録が、ローカルに記録されています。';status.textContent='新しく申し込む必要はありません。'}
start.addEventListener('click',async()=>{if(busy)return;const epoch=begin();try{if(!window.PublicKeyCredential||!navigator.credentials)throw Error('authenticator');status.textContent='登録する認証器で本人確認をしてください。';const value=challenge(await api('start'),'registration');if(epoch!==generation)return;ceremonyID=value.ceremonyID;check.hidden=false;armExpiry(value.expiresAt);const cred=await navigator.credentials.create({publicKey:{challenge:decode(value.challenge),rp:{id:value.rpId,name:'ねこのまど運営'},user:{id:decode(value.userID),name:'運営者',displayName:'運営者'},pubKeyCredParams:[{type:'public-key',alg:-7}],authenticatorSelection:{authenticatorAttachment:'cross-platform',residentKey:'discouraged',userVerification:'required'},attestation:'none',timeout:Math.min(60000,value.expiresAt*1000-Date.now())},signal:controller.signal});if(epoch!==generation)return;if(!cred||cred.type!=='public-key')throw Error('credential');credentialID=new Uint8Array(cred.rawId);const proof={id:cred.id,rawId:encode(cred.rawId),type:cred.type,clientExtensionResults:cred.getClientExtensionResults(),response:{clientDataJSON:encode(cred.response.clientDataJSON),attestationObject:encode(cred.response.attestationObject)}};if(cred.authenticatorAttachment)proof.authenticatorAttachment=cred.authenticatorAttachment;if(typeof cred.response.getTransports==='function')proof.response.transports=cred.response.getTransports();const value2=await api('ceremonies/'+ceremonyID+'/registration',JSON.stringify(proof));if(epoch!==generation)return;next=challenge(value2,'possession');steps(2);start.hidden=true;possession.hidden=false;status.textContent='鍵を登録しました。同じ認証器で、鍵を使えることを確認してください。';byId('heading').textContent='同じ鍵で所有を確認';byId('instruction').textContent='登録した認証器をそのまま使ってください。まだ運営者登録は確定していません。';}catch{if(epoch===generation)failed()}finally{if(epoch===generation){lock(false);if(!next)start.disabled=true}}});
possession.addEventListener('click',async()=>{if(busy||!next||!credentialID)return;const epoch=begin();const value=next;try{status.textContent='同じ認証器で所有確認をしてください。';const cred=await navigator.credentials.get({publicKey:{challenge:decode(value.challenge),rpId:value.rpId,userVerification:'required',allowCredentials:[{type:'public-key',id:credentialID}],timeout:Math.min(60000,value.expiresAt*1000-Date.now())},signal:controller.signal});if(epoch!==generation)return;if(!cred||cred.type!=='public-key')throw Error('credential');const proof={id:cred.id,rawId:encode(cred.rawId),type:cred.type,clientExtensionResults:cred.getClientExtensionResults(),response:{clientDataJSON:encode(cred.response.clientDataJSON),authenticatorData:encode(cred.response.authenticatorData),signature:encode(cred.response.signature)}};if(cred.authenticatorAttachment)proof.authenticatorAttachment=cred.authenticatorAttachment;const data=await api('ceremonies/'+ceremonyID+'/possession',JSON.stringify(proof));if(epoch!==generation)return;next=null;credentialID=null;showRequest(data);}catch{if(epoch===generation)failed()}finally{if(epoch===generation)lock(false)}});
byId('download').addEventListener('click',()=>{if(!request||busy)return;const blob=new Blob([JSON.stringify(request,null,2)+'\\n'],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='operator-enrollment-'+request.requestID+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),0)});
admit.addEventListener('click',async()=>{if(busy||!request)return;const raw=signatures.value;if(new TextEncoder().encode(raw).length>4096){status.textContent='承認署名のファイル内容を確認してください。';return}const epoch=begin();try{status.textContent='承認署名と現在の権限を照合しています…';const value=await api('requests/'+request.requestID+'/admit',raw);if(epoch!==generation)return;showReceipt(value);}catch{if(epoch===generation)failed()}finally{if(epoch===generation)lock(false)}});
check.addEventListener('click',async()=>{if(busy||!ceremonyID)return;const epoch=begin();hideDetails();try{status.textContent='同じ申込の記録を確認しています…';const data=await api('ceremonies/'+ceremonyID+'/status');if(epoch!==generation)return;if(data.ceremonyID&&data.ceremonyID!==ceremonyID)throw Error('binding');if(data.status==='admitted'){if(data.request)showRequest(data.request,true);showReceipt(data.receipt)}else if(data.status==='pending'&&data.request){showRequest(data.request)}else if(['attempted','expired','not_found'].includes(data.status)){start.disabled=true;status.textContent=data.status==='expired'?'この申込の有効期限が過ぎています。現在の権限はこの記録だけでは確認できません。':data.status==='attempted'?'署名照合の試行が記録されています。登録の確定は確認できません。同じ署名は再送しません。':'登録が確定した記録を確認できません。運営用の接続と準備状況を確認してください。'}else throw Error('status');}catch{if(epoch===generation)failed()}finally{if(epoch===generation){lock(false);start.disabled=true}}});
</script></body></html>`, {headers: {
    "Content-Type": "text/html; charset=utf-8", "Cache-Control": "no-store",
    "Content-Security-Policy": `default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'`,
    "Referrer-Policy": "no-referrer", "X-Content-Type-Options": "nosniff", "X-Frame-Options": "DENY",
  }});
}
